apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-depl
spec:
  selector:
    matchLabels:
      app: listing
  template:
    metadata:
      labels:
        app: listing
    spec:
      # Init container to ensure RabbitMQ is ready
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq-srv 5672; do echo waiting for rabbitmq; sleep 2; done;",
            ]
      containers:
        - name: listing-depl
          image: nody00/autobuy-listing
          ports:
            - containerPort: 4002
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwtSecret
            - name: COOKIE_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: cookieKey
---
apiVersion: v1
kind: Service
metadata:
  name: listing-clusterip-srv
spec:
  selector:
    app: listing
  ports:
    - name: listing
      protocol: TCP
      port: 4002
      targetPort: 4002
