apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      # Init container to ensure RabbitMQ is ready
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq-srv 5672; do echo waiting for rabbitmq; sleep 2; done;",
            ]
          resources:
            limits:
              memory: "64Mi"
            requests:
              memory: "32Mi"
      containers:
        - name: query-depl
          image: nody00/autobuy-query
          ports:
            - containerPort: 4003
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "300Mi"
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwtSecret
            - name: COOKIE_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: cookieKey
            - name: REFRESH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: refresh-jwt-secret
                  key: refreshJwtSecret
---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4003
      targetPort: 4003
